version: "3.5"

services:
    # https://hub.docker.com/_/nginx/
    www:
        image: nginx:1.13-alpine
        ports:
            - "80:80"

    # https://hub.docker.com/r/miveo/centos-php-fpm/
    php:
        image: miveo/centos-php-fpm:7.2-no-xdebug

    # https://hub.docker.com/r/kkarczmarczyk/node-yarn/
    yarn:
        image: kkarczmarczyk/node-yarn:8.0-slim
        command: bash -c "yarn install && yarn build"

    # https://hub.docker.com/_/postgres/
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_PORT=${DATABASE_PORT}
        ports:
            - "5432:5432"
